#include "GenericLevel.h"
#include "Player.h"
#include "Bullet.h"
#include "Enemy.h"

/**
 * This file is procedurally generated by a python script from the level definitions.
 * TODO: Move the level definitions to an external XML file.
 */

// LEVEL 1
BulletRules level1Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level1Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	0, // rotational velocity
	48, // fire interval
	ofPoint(0, -12), // fire velocity
	&level1Player1BulletRules,
};
EnemyRules level1EnemyRules =
{
	32, // radius
	0.3, // speed
};
GenericLevelRules level1Rules =
{
	// players
	{
		&level1Player1Rules,
	},
	1, // player count
	10, // enemy count
	&level1EnemyRules,
	NULL, // instructions
	255, // gravity arrow alpha
	255, // path projection alpha
	100, // path projection count
};

// LEVEL 2
BulletRules level2Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level2Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	0, // rotational velocity
	36, // fire interval
	ofPoint(0, -12), // fire velocity
	&level2Player1BulletRules,
};
EnemyRules level2EnemyRules =
{
	28, // radius
	0.35, // speed
};
GenericLevelRules level2Rules =
{
	// players
	{
		&level2Player1Rules,
	},
	1, // player count
	13, // enemy count
	&level2EnemyRules,
	NULL, // instructions
	191, // gravity arrow alpha
	191, // path projection alpha
	75, // path projection count
};

// LEVEL 3
BulletRules level3Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level3Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	-90, // initial rotation
	0, // rotational velocity
	26, // fire interval
	ofPoint(0, -12), // fire velocity
	&level3Player1BulletRules,
};
EnemyRules level3EnemyRules =
{
	24, // radius
	0.4, // speed
};
GenericLevelRules level3Rules =
{
	// players
	{
		&level3Player1Rules,
	},
	1, // player count
	14, // enemy count
	&level3EnemyRules,
	NULL, // instructions
	127, // gravity arrow alpha
	127, // path projection alpha
	50, // path projection count
};

// LEVEL 4
BulletRules level4Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level4Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	90, // initial rotation
	0, // rotational velocity
	18, // fire interval
	ofPoint(0, -12), // fire velocity
	&level4Player1BulletRules,
};
EnemyRules level4EnemyRules =
{
	20, // radius
	0.45, // speed
};
GenericLevelRules level4Rules =
{
	// players
	{
		&level4Player1Rules,
	},
	1, // player count
	17, // enemy count
	&level4EnemyRules,
	NULL, // instructions
	63, // gravity arrow alpha
	63, // path projection alpha
	25, // path projection count
};

// LEVEL 5
BulletRules level5Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level5Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	180, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level5Player1BulletRules,
};
EnemyRules level5EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level5Rules =
{
	// players
	{
		&level5Player1Rules,
	},
	1, // player count
	20, // enemy count
	&level5EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 6
BulletRules level6Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level6Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 160),
		ofPoint(160, 320),
	},
	2, // waypoint count
	0.5, // speed
	90, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level6Player1BulletRules,
};
EnemyRules level6EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level6Rules =
{
	// players
	{
		&level6Player1Rules,
	},
	1, // player count
	25, // enemy count
	&level6EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 7
BulletRules level7Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level7Player1Rules =
{
	// waypoints
	{
		ofPoint(100, 180),
		ofPoint(220, 180),
		ofPoint(220, 300),
		ofPoint(100, 300),
	},
	4, // waypoint count
	0.5, // speed
	0, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level7Player1BulletRules,
};
EnemyRules level7EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level7Rules =
{
	// players
	{
		&level7Player1Rules,
	},
	1, // player count
	25, // enemy count
	&level7EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 8
BulletRules level8Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level8Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	0.1, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level8Player1BulletRules,
};
EnemyRules level8EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level8Rules =
{
	// players
	{
		&level8Player1Rules,
	},
	1, // player count
	25, // enemy count
	&level8EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 9
BulletRules level9Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level9Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 240),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	-0.2, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level9Player1BulletRules,
};
EnemyRules level9EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level9Rules =
{
	// players
	{
		&level9Player1Rules,
	},
	1, // player count
	25, // enemy count
	&level9EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 10
BulletRules level10Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level10Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 160),
		ofPoint(160, 320),
	},
	2, // waypoint count
	0.5, // speed
	0, // initial rotation
	-0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level10Player1BulletRules,
};
EnemyRules level10EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level10Rules =
{
	// players
	{
		&level10Player1Rules,
	},
	1, // player count
	30, // enemy count
	&level10EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 11
BulletRules level11Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level11Player1Rules =
{
	// waypoints
	{
		ofPoint(100, 180),
		ofPoint(220, 180),
		ofPoint(220, 300),
		ofPoint(100, 300),
	},
	4, // waypoint count
	0.5, // speed
	0, // initial rotation
	0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level11Player1BulletRules,
};
EnemyRules level11EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level11Rules =
{
	// players
	{
		&level11Player1Rules,
	},
	1, // player count
	35, // enemy count
	&level11EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 12
BulletRules level12Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level12Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 160),
	},
	1, // waypoint count
	0.5, // speed
	90, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level12Player1BulletRules,
};
BulletRules level12Player2BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level12Player2Rules =
{
	// waypoints
	{
		ofPoint(160, 320),
	},
	1, // waypoint count
	0.5, // speed
	90, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level12Player2BulletRules,
};
EnemyRules level12EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level12Rules =
{
	// players
	{
		&level12Player1Rules,
		&level12Player2Rules,
	},
	2, // player count
	55, // enemy count
	&level12EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 13
BulletRules level13Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level13Player1Rules =
{
	// waypoints
	{
		ofPoint(100, 180),
		ofPoint(220, 180),
		ofPoint(220, 300),
		ofPoint(100, 300),
	},
	4, // waypoint count
	0.5, // speed
	180, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level13Player1BulletRules,
};
BulletRules level13Player2BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level13Player2Rules =
{
	// waypoints
	{
		ofPoint(220, 300),
		ofPoint(100, 300),
		ofPoint(100, 180),
		ofPoint(220, 180),
	},
	4, // waypoint count
	0.5, // speed
	180, // initial rotation
	0, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level13Player2BulletRules,
};
EnemyRules level13EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level13Rules =
{
	// players
	{
		&level13Player1Rules,
		&level13Player2Rules,
	},
	2, // player count
	60, // enemy count
	&level13EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 14
BulletRules level14Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level14Player1Rules =
{
	// waypoints
	{
		ofPoint(160, 160),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	-0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level14Player1BulletRules,
};
BulletRules level14Player2BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level14Player2Rules =
{
	// waypoints
	{
		ofPoint(160, 320),
	},
	1, // waypoint count
	0.5, // speed
	0, // initial rotation
	-0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level14Player2BulletRules,
};
EnemyRules level14EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level14Rules =
{
	// players
	{
		&level14Player1Rules,
		&level14Player2Rules,
	},
	2, // player count
	65, // enemy count
	&level14EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// LEVEL 15
BulletRules level15Player1BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level15Player1Rules =
{
	// waypoints
	{
		ofPoint(100, 180),
		ofPoint(220, 180),
		ofPoint(220, 300),
		ofPoint(100, 300),
	},
	4, // waypoint count
	0.5, // speed
	180, // initial rotation
	0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level15Player1BulletRules,
};
BulletRules level15Player2BulletRules =
{
	7, // radius
	0.8, // gravity factor
};
PlayerRules level15Player2Rules =
{
	// waypoints
	{
		ofPoint(220, 300),
		ofPoint(100, 300),
		ofPoint(100, 180),
		ofPoint(220, 180),
	},
	4, // waypoint count
	0.5, // speed
	180, // initial rotation
	0.25, // rotational velocity
	12, // fire interval
	ofPoint(0, -12), // fire velocity
	&level15Player2BulletRules,
};
EnemyRules level15EnemyRules =
{
	16, // radius
	0.5, // speed
};
GenericLevelRules level15Rules =
{
	// players
	{
		&level15Player1Rules,
		&level15Player2Rules,
	},
	2, // player count
	70, // enemy count
	&level15EnemyRules,
	NULL, // instructions
	0, // gravity arrow alpha
	0, // path projection alpha
	0, // path projection count
};

// 15 LEVELS.
GenericLevelRules* levels[] =
{
	&level1Rules,
	&level2Rules,
	&level3Rules,
	&level4Rules,
	&level5Rules,
	&level6Rules,
	&level7Rules,
	&level8Rules,
	&level9Rules,
	&level10Rules,
	&level11Rules,
	&level12Rules,
	&level13Rules,
	&level14Rules,
	&level15Rules,
};
